Bump graphql-core to 3.2.0 (#283)
* Fix error 'graphql.error.graphql_error.GraphQLError: Names must only contain [_a-zA-Z0-9] but 'meta-field' does not.'

* Don't use format_error

* Put the is_finite method in the test file

* Fix StarWars schema

Fixes 'Support for returning GraphQLObjectType from resolve_type was removed in GraphQL-core 3.2, please return type name instead'

* fix print_ast removing last newline

* Fix error: AttributeError: 'ParseResultVisitor' object has no attribute 'enter_leave_map'

* Rename specifiedByUrl to specifiedByURL

See https://github.com/graphql/graphql-js/issues/3156

* Bump graphql-core version to stable 3.2

This new version of GraphQL-core replaces the FrozenLists in AST nodes
with tuples, so we need to make the appropriate changes in dsl.py.

* Fix Introspection directive typing