Allways pull in deps for working gql-cli
As things stand:

```
$ pip3 install gql

$ echo 'query { continent(code:"AF") { name } }' | gql-cli https://countries.trevorblades.com
Traceback (most recent call last):
  File "/home/steve/tests/bin/gql-cli", line 8, in <module>
    sys.exit(gql_cli())
             ~~~~~~~^^
  File "/home/steve/tests/lib64/python3.13/site-packages/gql/cli.py", line 534, in gql_cli
    exit_code = loop.run_until_complete(main_task)
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/steve/tests/lib64/python3.13/site-packages/gql/cli.py", line 436, in main
    transport = get_transport(args)
  File "/home/steve/tests/lib64/python3.13/site-packages/gql/cli.py", line 323, in get_transport
    from gql.transport.aiohttp import AIOHTTPTransport
  File "/home/steve/tests/lib64/python3.13/site-packages/gql/transport/aiohttp.py", line 9, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

The aiohttp dependencies are really allways needed for CLI to work.

This patch makes aiohttp an `install_require` rather than be required as an optional sub package.